Pandas Learning

In [1]:
import pandas as pd

Introduction to Dataframe

In [2]:
#We initialize datas in pandas:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"],index=["x","y","z"])

In [3]:
'''df.head(1) Accessing first 2 row
df.head(0) Accessing the row 0 
df.head(3) Accessing data upto row 3'''

df.head() #Accessing all elements in the dataframe
#df.head(2)

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [4]:
#df.tail(1)
df.tail(2)

   A  B  C
y  4  5  6
z  7  8  9

In [5]:
df.info()#Descritption of our dataframe

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [6]:
df.describe()#meaningful information of data of individual columns

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [7]:
df.nunique()#tota number of unique values in each column

A    3
B    3
C    3
dtype: int64

In [8]:
df['A'].unique()#Unique elements in specific column

array([1, 4, 7])

In [9]:
df['A'].nunique()#total no of unique values in specific column

3

In [10]:
df.shape #shape of dataframe

(3, 3)

In [11]:
df.size #size of dataframe

9

**Loading in Dataframes from files**

In [12]:
coffee=pd.read_csv('./coffee.csv')#Accessing csv file

In [13]:
results=pd.read_csv('./data/results.csv') #Accessing csv file
#('./folder_name/file_name')

In [14]:
olympics_data=pd.read_excel('./data/olympics-data.xlsx') #Accessing excel file

In [15]:
results=pd.read_parquet('./data/results.parquet')#Accessing using parquet file which is compartively faster in accessing than csv and excel file.

**Accessing Data from File**

In [16]:
olympics_data.head() #.head returns first 5 rows of a file

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [17]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [18]:
results.head(3) #It returns only first 3 rows

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN

In [19]:
coffee.tail(3) #It returns last 3 rows

         Day Coffee Type  Units Sold
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [20]:
#Accessing random data:

coffee.sample(10)#It shows random data everytime we run this command
coffee.sample(10, random_state=1) #Using this (random state), data doesn't changes, it stablizes output data


#Try run both commands keeping one constant to make it more clear.

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

In [21]:
coffee #We can access the file using file name only too.

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [22]:
#Accessing specific data

coffee.loc[[1,3]] #loc stands for location

#It returns the data of row 1 and 3

       Day Coffee Type  Units Sold
1   Monday       Latte          15
3  Tuesday       Latte          20

In [23]:
coffee.loc[2:5] #from 2 to 5
coffee.loc[5:] #From 5 onwards

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [24]:
coffee.loc[2:5,["Day"]] #Accessing day from 2 to 5

         Day
2    Tuesday
3    Tuesday
4  Wednesday
5  Wednesday

In [25]:
coffee.loc[2:8,["Day","Coffee Type"]]

         Day Coffee Type
2    Tuesday    Espresso
3    Tuesday       Latte
4  Wednesday    Espresso
5  Wednesday       Latte
6   Thursday    Espresso
7   Thursday       Latte
8     Friday    Espresso

In [26]:
#Accessing using iloc means index location
coffee.iloc[2:8, [0,2]] #[0,2] are index location  of column name

         Day  Units Sold
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35
5  Wednesday          25
6   Thursday          40
7   Thursday          30

In [27]:
#loc allows us to access rows and columns
#iloc allows us to access rows and columns only using index values

In [28]:
'''#Modifying values 
coffee.loc[1:3,"Unit Sold"] = 70 #Modifying unit sold of index 3
coffee.head()'''

'#Modifying values \ncoffee.loc[1:3,"Unit Sold"] = 70 #Modifying unit sold of index 3\ncoffee.head()'

In [29]:
coffee.head() #Re run the mathiko coffee.csv file again to get the original data

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [30]:
#Accessing one single specific value
coffee.iat[1,1]

'Latte'

In [31]:
#Sorting values:
coffee.sort_values("Units Sold") #For ascending

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [32]:
coffee.sort_values("Units Sold",ascending=False)#For descending

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [33]:
#Sorting two columns where coffee type is descending and units sold is ascending
coffee.sort_values(["Coffee Type","Units Sold"],ascending=[0,1])

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
5   Wednesday       Latte          25
7    Thursday       Latte          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
0      Monday    Espresso          25
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

**Filtering Data**

In [34]:
bios=pd.read_csv("./data/bios.csv")

In [35]:
#with loc
bios.loc[bios['height_cm']>220,['name','height_cm']]

                   name  height_cm
5673     Gunther Behnke      221.0
5781     Tommy Burleson      223.0
6978    Arvydas Sabonis      223.0
89070          Yao Ming      226.0
89075    Roberto Dueñas      221.0
120266     Zhang Zhaoxu      221.0

In [36]:
#Without loc
bios[bios['height_cm'] > 220][['name','height_cm']]

                   name  height_cm
5673     Gunther Behnke      221.0
5781     Tommy Burleson      223.0
6978    Arvydas Sabonis      223.0
89070          Yao Ming      226.0
89075    Roberto Dueñas      221.0
120266     Zhang Zhaoxu      221.0

In such way we can filter any data from huge dataframe

In [37]:
#Filtering the data using multiple conditions
bios[(bios['height_cm']>215) & (bios['born_country']=='USA')][['name','height_cm','born_country']]

                    name  height_cm born_country
5781      Tommy Burleson      223.0          USA
6722    Shaquille O'Neal      216.0          USA
6937      David Robinson      216.0          USA
123850    Tyson Chandler      216.0          USA

In [38]:
bios[bios['name'].str.contains('suman',case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
44062,44401,Angsuman Chotisathein,1949-07-21,NaN,NaN,NaN,Thailand,159.0,51.0,NaN
74539,75111,Mariana Suman,1951-07-29,Roman,Neamț,ROU,Romania,164.0,54.0,NaN
89200,89912,Adama Osumanu,1980-12-24,Accra,Greater Accra,GHA,Ghana,190.0,71.0,NaN
100345,101195,Christoph Sumann,1976-01-19,Judenburg,Steiermark,AUT,Austria,182.0,80.0,NaN
101881,102811,Sumangala Sharma,1986-12-30,NaN,NaN,NaN,India,165.0,53.0,NaN
137047,140283,Stribor Suman,2002-03-05,NaN,NaN,NaN,Croatia,NaN,NaN,NaN

In [39]:
bios[bios['born_country'] == 'NEP'][['name','born_country','born_city']]

                         name born_country         born_city
3860           Debendra Thapa          NEP           Syangja
4731             Umesh Maskey          NEP         Kathmandu
4732           Nam Sing Thapa          NEP        Manakamana
4735        Ram Prasad Gurung          NEP  Daraun-Sirubari
43132           Parvati Thapa          NEP         Nepalgunj
56014          Surendra Hamal          NEP         Nepalgunj
56015             Sunil Joshi          NEP         Kathmandu
73363        Bhupendra Silwal          NEP            Sankhu
73369     Baikuntha Manandhar          NEP         Kathmandu
73373             Hari Rokaya          NEP             Jumla
73376     Ganga Bahadur Thapa          NEP          Pharping
100599             Jay Khadka          NEP          Bansbari
102387          Nayana Shakya          NEP         Kathmandu
107025         Sangina Baidya          NEP         Kathmandu
110493  Phool Maya Kyapchhaki          NEP  Dhanusa district
111411             Devu Thapa          NEP             Jumla
113481          Chandra Thapa          NEP          Urlabari
114178     Arjun Kumar Basnet          NEP            Kangel
114565         Prasiddha Shah          NEP         Kathmandu
114675         Karishma Karki          NEP         Kathmandu
115015         Kamal Adhikari          NEP         Gitanagar
120230        Tilak Ram Tharu          NEP  Chitwan District
120391          Pramila Rijal          NEP         Chisapani
128667      Phupu Lamu Khatri          NEP         Kathmandu
128668          Gaurika Singh          NEP          Lalitpur
128669            Nisha Rawal          NEP         Kathmandu
131635               Jitu Rai          NEP     Sankhuwasabha
132424          Sirish Gurung          NEP         Kathmandu

**Adding and Removing column**

In [40]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [41]:
coffee_new=coffee.copy() #we have to create a new dataframe because changing in old ones changes whole dataframe and their respective output

In [42]:
coffee_new['price in $']=5 #price in $ is the added column

In [43]:
coffee_new.head()

         Day Coffee Type  Units Sold  price in $
0     Monday    Espresso          25           5
1     Monday       Latte          15           5
2    Tuesday    Espresso          30           5
3    Tuesday       Latte          20           5
4  Wednesday    Espresso          35           5

Changing price of multiple items

In [44]:
'''
import numpy as np
coffee_new['new_price']=np.where(coffee_new['Coffee Type']=='Espresso',3.99,4.00)
coffee_new'''

"\nimport numpy as np\ncoffee_new['new_price']=np.where(coffee_new['Coffee Type']=='Espresso',3.99,4.00)\ncoffee_new"

In [45]:
'''#To drop a column:
#Command:

coffee_new.drop(columns=['Units Sold'], inplace=True)
coffee_new

#We drop the column 'Units Sold' once we run this command so better rerun the above command 
#to get the original data'''

"#To drop a column:\n#Command:\n\ncoffee_new.drop(columns=['Units Sold'], inplace=True)\ncoffee_new\n\n#We drop the column 'Units Sold' once we run this command so better rerun the above command \n#to get the original data"

In [46]:
#We can calculate the terms inside dataframe such as revenue like this:
coffee_second_new=coffee_new.copy()
coffee_second_new['revenue']=coffee_second_new['Units Sold']*coffee_second_new['price in $']

In [47]:
coffee_second_new #The reason we are naming this coffee_second_new so that we can clearly see the changes.

          Day Coffee Type  Units Sold  price in $  revenue
0      Monday    Espresso          25           5      125
1      Monday       Latte          15           5       75
2     Tuesday    Espresso          30           5      150
3     Tuesday       Latte          20           5      100
4   Wednesday    Espresso          35           5      175
5   Wednesday       Latte          25           5      125
6    Thursday    Espresso          40           5      200
7    Thursday       Latte          30           5      150
8      Friday    Espresso          45           5      225
9      Friday       Latte          35           5      175
10   Saturday    Espresso          45           5      225
11   Saturday       Latte          35           5      175
12     Sunday    Espresso          45           5      225
13     Sunday       Latte          35           5      175

In [48]:
#Renaming a column:

coffee_second_new.rename(columns={'price in $':'price'},inplace=True) #

C:\Users\olisu\AppData\Local\Temp\ipykernel_21040\1889738491.py:3: Pandas4Warning: The inplace keyword in DataFrame.rename is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  coffee_second_new.rename(columns={'price in $':'price'},inplace=True) #

So without inplace the command only shows the results in this one's output only and doesn't changes the whole coffee_second_new table, but after using (inplace=True) the changes are permanently saved and show the changes in the output whenever we want.

In [49]:
coffee_second_new

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25      5      125
1      Monday       Latte          15      5       75
2     Tuesday    Espresso          30      5      150
3     Tuesday       Latte          20      5      100
4   Wednesday    Espresso          35      5      175
5   Wednesday       Latte          25      5      125
6    Thursday    Espresso          40      5      200
7    Thursday       Latte          30      5      150
8      Friday    Espresso          45      5      225
9      Friday       Latte          35      5      175
10   Saturday    Espresso          45      5      225
11   Saturday       Latte          35      5      175
12     Sunday    Espresso          45      5      225
13     Sunday       Latte          35      5      175

In [50]:
bios_new=bios.copy()

In [51]:
bios_new['first_name']=bios_new['name'].str.split(' ').str[0]
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [52]:
bios_new.query('first_name=="Keith"') #WE can see keith only if we scroll right in the first_name section

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

In [53]:
bios_new['DOB']=pd.to_datetime(bios_new['born_date'])#Conveting the born_date to 'to_datetime' so that we can point out born_year
bios_new['born_year']=bios_new['DOB'].dt.year
bios_new[['name','born_year']].head()

                    name  born_year
0  Jean-François Blanchy     1886.0
1         Arnaud Boetsch     1969.0
2           Jean Borotra     1898.0
3        Jacques Brugnon     1895.0
4           Albert Canet     1878.0

In [54]:
bios_new.to_csv('./data/bios_new',index=False) #Making a new csv dataframe: bios_new stored in data folder

In [55]:
#Adding a new column(height_category) in bios dataframe
bios_new['height_category']=bios_new['height_cm'].apply(lambda x: 'Short' if x < 170 else 'Average' if x < 185 else 'Tall')
bios_new.head(8)

#Scroll to the right to see the result and learn the pattern how we calculate height_categorya and born_year.

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,DOB,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Short
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,Nicolas,1970-01-13,1970.0,Average
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN,Patrick,1969-11-27,1969.0,Average
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02,Henri,1901-12-14,1901.0,Tall

In [56]:
#In this way we can apply conditions too using function:

def athelete_category(row):
    if row['height_category']=='short' or row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_category']=='Average' or row['weight_kg'] < 75:
         return 'Middleweight'
    else:
        return 'Heavyweight'

bios_new['category']=bios_new.apply(athelete_category, axis=1)
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,DOB,born_year,height_category,category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Short,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall,Heavyweight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30,2002.0,Short,Lightweight
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20,1999.0,Short,Lightweight
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08,1998.0,Short,Lightweight
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19,1899.0,Short,Heavyweight
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15,1913.0,Tall,Heavyweight

**Merging and Concatenating Data**

In [57]:
#Reading a noc_regions file from data folder
noc=pd.read_csv('./data/noc_regions.csv')
noc.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [58]:
#Merging bios_new file with noc file and store them in bios_new_new file
bios_new_new=bios_new.copy()
bios_new_new=pd.merge(bios_new, noc,left_on='born_country',right_on='NOC' ,how='left')
bios_new_new.head()

#we merge (born_country) of bios_new dataframe with 'NOC' of noc dataframe. 
#we use (left_on = born_country) and (right_on = NOC) in this code because these two dataframehave
# same values in these both columns that helps us to merge it taking the values as reference.

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,first_name,DOB,born_year,height_category,category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,Heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,Middleweight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,Middleweight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Short,Lightweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall,Heavyweight,GBR,UK,NaN

In [59]:
bios_new_new.rename(columns={'region':'born_country_full'},inplace=True)
bios_new_new.head()

C:\Users\olisu\AppData\Local\Temp\ipykernel_21040\1676656435.py:1: Pandas4Warning: The inplace keyword in DataFrame.rename is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  bios_new_new.rename(columns={'region':'born_country_full'},inplace=True)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,first_name,DOB,born_year,height_category,category,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,Heavyweight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,Middleweight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,Middleweight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Short,Lightweight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall,Heavyweight,GBR,UK,NaN

In [60]:
#Creating a new df so that we can concat
usa=bios[bios['born_country']=='USA'].copy()
gbr=bios[bios['born_country']=='GBR'].copy()

In [61]:
#Concatenating usa and gbr dataframe
new_df=pd.concat([usa,gbr])

In [62]:
new_df.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN

In [63]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN

In [64]:
#Merging results dataframe with bios dataframe
combined_df=pd.merge(results,bios, on='athlete_id',how='left')

#In this merging we have shared column name (athlete_id) in both dataframes so no need to specify left_on and right_on

In [65]:
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02

**Handling Null Value**

In [78]:
import numpy as np
coffee.loc[[3,4],'Units Sold']=np.nan
coffee

#2 and 3 are deleted just before so it is not appeared

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
3     Tuesday       Latte         NaN
4   Wednesday    Espresso         NaN
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [79]:
#Removing null value using interpolate(): 

#coffee['Units Sold']=coffee['Units Sold'].interpolate()
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
3     Tuesday       Latte         NaN
4   Wednesday    Espresso         NaN
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [68]:
#or we can just drop the NaN values usning following code:

#coffee.dropna() #It just drop the full enitre rows that contains null values

#Check this command while commenting upper one so that we can see the changes clearly.

In [ ]:
coffee[coffee['Units Sold'].isna()]
#filtering the rows that contains NaN values.

         Day Coffee Type  Units Sold
3    Tuesday       Latte         NaN
4  Wednesday    Espresso         NaN

In [84]:
coffee[coffee['Units Sold'].notna()]
#rows that doesn't contains NaN or null values.

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

**Aggregating Data**